enhancement(UsedSpace): Make the chunk store's UsedSpace struct async safe
maidsafe/sn_node pull request #1105
Opened 2020-09-19 11:31 UTC by Scorch-Dev

Simplifies the passing of `used_space` to chunk stores. It creates a shared `UsedSpace` instance which is a thin wrapper to an `Arc<Mutex<UsedSpace>>` and synchronizes access to the global amount of used space (`total_value` and `max_capacity` in code today) and the individual used space for each chunk store. 

**Quick Benefits**
* Paves the way for *proper* `ChunkStore` concurrency (see "Motivation" section below)
* Less implementation bleeding to other modules
    * e.g. no more passing around `Arc<Mutex<u64>> used_space` everywhere. Instead just becomes `used_space.clone()`
* reduced redundancy of shared state and less prone to related bugs
    * e.g. no more need to pass `maximum_capacity` to `ChunkStore` objects, giving each there own copy, which could potentially fall out of sync if it were ever needed to be changed

## Motivation

This doesn't seem to be covered in the big [asysnc PR](https://github.com/maidsafe/safe-vault/pull/1103), which only seems to cover mostly things related to qp2p. Currently, the struct `ChunkStore<TChunk>` is not async safe. So while many of their functions may be denoted `async` after that linked PR is merged, the vault doesn't currently have the flexibility to leverage concurrency for multiple vault operations. 

Thus, statements like the following, or potential architectural changes of similar nature would not be possible, limiting the vault's potential for performance:

    // Currently, not possible (even after PR merges)
    let tasks = Vec::new();
    for _ in 0..10 {
        tasks.push( chunk_store.do_concurrent_operation() );
    }
    future::futures::try_join_all(&tasks).await?

Instead, we would need something like the following, code, which would `await` each operation, which could otherwise be run concurrently, before running the next.

    // Only this is possible right now (even after PR merges)
    for _ in 0..10 {
        chunk_store.do_operation().await;
   }

So the current architecture allows concurrency for connections, it's still limiting for chunk store operations.

The first step to enabling chunk store operations to run concurrently, is to simplify the interface to `UsedSpace`, so the `local_value` of the `UsedSpace` struct that each `ChunkStore<T>` holds, as well as the file `used_space` for each chunk store, tracks properly across multiple operations on potentially separate threads.

## Related

I mentioned this briefly in a couple of places, and it's currently not a part of the [`async` PR](https://github.com/maidsafe/safe-vault/pull/1103) as I mentioned above. I did mention it [here](https://forum.safedev.org/t/still-using-synchronous-file-i-o-in-vaults/2881) in the forums and in a git issue I raised earlier, #1094 and alluded to in and PR #1090. This PR is part of #1094  but doesn't fully close it per say, but it would be the first step.

2020-09-24 11:12 UTC, joshuef commented
@Scorch-Dev thanks for this.

And just so you're aware. Currently digging in to CI e2e failures. Once we have that in / straightened out we'll be able to verify this against the CI better (the ubuntu fail is almost certainly the same).

Will get to this asap after that 👍

2020-09-24 11:35 UTC, Scorch-Dev commented
@joshuef No worries, and thanks for the heads up 👍

2020-09-28 11:30 UTC, joshuef requested changes
Overall great PR with a lot docs and explanations. Thanks @Scorch-Dev  

Few wee things to tweak to stay consistent with how we're looking to approach tests. I've added some suggestions for those 👍 .

2020-09-28 11:30 UTC, joshuef commented on src/chunk_store/tests.rs
> +        unwrap!(ChunkStore::<Data>::new(root.path(), used_space.clone(), Init::New).await);
@Scorch-Dev we're currently striving to cleanup tests, to return a `Result` type. Would be great to use that here instead of `unwrap`.
```suggestion
        ChunkStore::<Data>::new(root.path(), used_space.clone(), Init::New).await?;
```

2020-09-28 11:30 UTC, joshuef commented on src/chunk_store/tests.rs
> +        unwrap!(ChunkStore::new(root.path(), used_space.clone(), Init::New).await);
```suggestion
        ChunkStore::new(root.path(), used_space.clone(), Init::New).await?;
```

2020-09-28 11:30 UTC, joshuef commented on src/chunk_store/tests.rs
> +        unwrap!(ChunkStore::new(root.path(), used_space.clone(), Init::New).await);
```suggestion
        ChunkStore::new(root.path(), used_space.clone(), Init::New).await?;
```

2020-09-28 11:30 UTC, joshuef commented on src/chunk_store/tests.rs
> +        unwrap!(ChunkStore::new(root.path(), used_space.clone(), Init::New).await);
```suggestion
        ChunkStore::new(root.path(), used_space.clone(), Init::New).await?;
```

2020-09-28 11:30 UTC, joshuef commented on src/chunk_store/used_space.rs
> +    /// consistentcy across local `ChunkStore`s
```suggestion
    /// consistency across local `ChunkStore`s
```

2020-09-28 11:47 UTC, lionel1704 reviewed
Nice one @Scorch-Dev. Great work. 
Once @joshuef's comments are addressed, we can get this in.

2020-09-28 12:51 UTC, lionel1704 approved these changes

2020-09-28 12:52 UTC, merged