Update to the latest qp2p API
maidsafe/sn_node pull request #1295
Opened 2021-02-15 08:39 UTC by lionel1704

- this also applies rustfmt and clippy fixes with the latest version of
routing

2021-02-15 08:56 UTC, Yoga07 approved these changes

2021-02-15 10:30 UTC, joshuef requested changes
code lgtm, but getting failing tests with your client 1378 pr still :(

2021-02-16 08:06 UTC, joshuef approved these changes

2021-02-16 08:35 UTC, joshuef approved these changes

2021-02-16 08:35 UTC, merged