Use destination accumulation for Elder to Adult communication
maidsafe/sn_node pull request #1305
Opened 2021-02-24 10:11 UTC by lionel1704

BREAKING CHANGE: this changes uses a new version of sn_messaging with a
breaking change

2021-02-24 15:00 UTC, joshuef commented
LGTM, but will need a routing release first

2021-02-24 17:02 UTC, oetyng requested changes
Yea it looks good! Just need corresponding `sn_messaging` and `sn_routing` changes merged and deps updated.

2021-02-25 11:15 UTC, joshuef submitted a review, later dismissed

2021-02-25 11:42 UTC, oetyng approved these changes

2021-02-25 11:56 UTC, merged